//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.remove(<quark:rune>);
recipes.remove(<quark:rune:1>);
recipes.remove(<quark:rune:2>);
recipes.remove(<quark:rune:3>);
recipes.remove(<quark:rune:4>);
recipes.remove(<quark:rune:5>);
recipes.remove(<quark:rune:11>);
recipes.remove(<quark:rune:14>);
recipes.remove(<quark:rune:16>);
recipes.remove(<mcwtrpdoors:metal_full_trapdoor>);
recipes.remove(<mcwtrpdoors:metal_trapdoor>);
recipes.remove(<mcwdoors:metal_reinforced_door>);
recipes.remove(<mcwdoors:metal_door>);
recipes.remove(<craftable_ender_pearls:soul_in_a_bottle>);
recipes.remove(<mekanism:ingot:3>);
recipes.remove(<srparasites:evolutionlure>);
recipes.remove(<nocubessrparmory:twistedpart>);
recipes.remove(<betterbuilderswands:wanddiamond>);
recipes.remove(<betterbuilderswands:wandunbreakable>);
recipes.remove(<betterbuilderswands:wandiron>);
recipes.remove(<betterbuilderswands:wandstone>);
recipes.remove(<playerplates:obsidian_plate>);
recipes.remove(<xplosives:packed_tnt>);
recipes.remove(<xplosives:hand_cannon>);
recipes.remove(<xplosives:detonator>);
recipes.remove(<xplosives:detonator_remote>);
recipes.remove(<xplosives:physics_bomb>);
recipes.remove(<xplosives:arrow_bomb>);
recipes.remove(<xplosives:bonemeal_bomb>);
recipes.remove(<ee:red_sword>);
recipes.remove(<travelersbackpack:travelers_backpack:57>);
recipes.remove(<xat:sea_stone>);
recipes.remove(<ee:end_door>);
recipes.remove(<nocubessrparmory:hosttentacle>);
recipes.remove(<swparasites:crossbow_living>);
recipes.remove(<swparasites:buckler_shield_living>);
recipes.remove(<swparasites:impaler_shield_living>);
recipes.remove(<wings:angel_wings>);
recipes.remove(<wings:dragon_wings>);
recipes.remove(<wings:evil_wings>);
recipes.remove(<wings:fairy_wings>);
recipes.remove(<wings:bat_wings>);
recipes.remove(<wings:fire_wings>);
recipes.remove(<wings:monarch_butterfly_wings>);
recipes.remove(<wings:blue_butterfly_wings>);
recipes.remove(<wings:slime_wings>);
recipes.remove(<hermitsarsenal:outbreak_dagger>);
recipes.remove(<hermitsarsenal:seismic_warhammer>);
recipes.remove(<hermitsarsenal:seizer_spear>);
recipes.remove(<hermitsarsenal:ignis_knife>);
recipes.remove(<hermitsarsenal:ignis_chakram>);
recipes.remove(<hermitsarsenal:longarm_appendage>);
recipes.remove(<hermitsarsenal:extended_appendage>);
recipes.remove(<hermitsarsenal:cytokine_mutator>);
recipes.remove(<hermitsarsenal:gene_desplicer>);
recipes.remove(<tconstruct:slime_boots:3>);
recipes.remove(<tconstruct:slime_boots:4>);
recipes.remove(<tconstruct:slime_boots:5>);
recipes.remove(<tconstruct:slime_boots>);
recipes.remove(<tconstruct:slime_boots:1>);
recipes.remove(<tconstruct:slime_boots:2>);
recipes.remove(<tconstruct:slimesling:1>);
recipes.remove(<tconstruct:slimesling>);
recipes.remove(<tconstruct:slimesling:2>);
recipes.remove(<tconstruct:slimesling:3>);
recipes.remove(<tconstruct:slimesling:4>);
recipes.remove(<srparasites:evolutionlure:9>);
recipes.remove(<srparasites:evolutionlure:8>);
recipes.remove(<srparasites:evolutionlure:7>);
recipes.remove(<srparasites:evolutionlure:6>);
recipes.remove(<srparasites:evolutionlure:5>);
recipes.remove(<srparasites:evolutionlure:4>);
recipes.remove(<srparasites:evolutionlure:3>);
recipes.remove(<srparasites:evolutionlure:2>);
recipes.remove(<xat:dragon_ring>);
recipes.remove(<xat:faelis_ring>);
recipes.remove(<xat:elf_ring>);
recipes.remove(<xat:goblin_ring>);
recipes.remove(<xat:titan_ring>);
recipes.remove(<xat:dwarf_ring>);
recipes.remove(<xat:fairy_ring>);
recipes.remove(<xat:restoration_serum>);
recipes.remove(<xat:dragons_eye>);
recipes.remove(<xat:poison_stone>);
recipes.remove(<xat:wither_ring>);
recipes.remove(<xat:wither_ring>);
recipes.remove(<xat:polarized_stone>);
recipes.remove(<xat:glow_ring>);
recipes.remove(<xat:greater_inertia_stone>);
recipes.remove(<bountifulbaubles:trinketobsidianskull>);
recipes.remove(<xat:mana_crystal>);
recipes.remove(<xat:damage_shield>);
recipes.remove(<xat:ender_tiara>);
recipes.remove(<xat:inertia_null_stone>);
recipes.remove(<xat:weightless_stone>);
recipes.remove(<xat:faelis_claw>);
recipes.remove(<xat:arcing_orb>);
recipes.remove(<xat:dragon_gem>);
recipes.remove(<xat:titan_spirit>);
recipes.remove(<xat:goblin_soup>);
recipes.remove(<xat:fairy_dew>);
recipes.remove(<xat:faelis_food>);
recipes.remove(<xat:elf_sap>);
recipes.remove(<xat:dwarf_stout>);
recipes.remove(<bountifulbaubles:trinketblackdragonscale>);
recipes.remove(<bountifulbaubles:amuletsinwrath>);
recipes.remove(<bountifulbaubles:crowngold>);
recipes.remove(<bountifulbaubles:amuletsinpride>);
recipes.remove(<bountifulbaubles:amuletsingluttony>);
recipes.remove(<bountifulbaubles:ringflywheeladvanced>);
recipes.remove(<bountifulbaubles:ringflywheel>);
recipes.remove(<bountifulbaubles:trinketankhcharm>);
recipes.remove(<improvableskills:skills_book>);
recipes.remove(<xat:mana_candy>);
recipes.remove(<travelersbackpack:travelers_backpack:22>);
recipes.remove(<spawnercraft:mob_rod>);
recipes.remove(<spawnercraft:mob_spirit>);
recipes.remove(<eplus:table_upgrade>);
recipes.remove(<eplus:advanced_table>);
recipes.remove(<srparasites:weapon_scythe>);
recipes.remove(<srparasites:weapon_axe>);
recipes.remove(<srparasites:weapon_sword>);
recipes.remove(<srparasites:weapon_cleaver>);
recipes.remove(<srparasites:weapon_bow>);
recipes.remove(<srparasites:weapon_scythe>);
recipes.remove(<swparasites:boomerang_living>);
recipes.remove(<swparasites:claymore_living>);
recipes.remove(<swparasites:dagger_living>);
recipes.remove(<swparasites:glaive_living>);
recipes.remove(<swparasites:halberd_living>);
recipes.remove(<swparasites:hammer_living>);
recipes.remove(<swparasites:hardened_bone_pole>);
recipes.remove(<swparasites:infectious_long_blade_fragment>);
recipes.remove(<swparasites:javelin_living>);
recipes.remove(<swparasites:katana_living>);
recipes.remove(<swparasites:longsword_living>);
recipes.remove(<swparasites:mace_living>);
recipes.remove(<swparasites:parrying_dagger_living>);
recipes.remove(<swparasites:pike_living>);
recipes.remove(<swparasites:rapier_living>);
recipes.remove(<swparasites:saber_living>);
recipes.remove(<swparasites:spear_living>);
recipes.remove(<swparasites:staff_living>);
recipes.remove(<swparasites:throwing_axe_living>);
recipes.remove(<swparasites:throwing_knife_living>);
recipes.remove(<swparasites:warhammer_living>);
recipes.remove(<mekanism:machineblock:11>);
recipes.remove(<mekanism:basicblock2:9>);
recipes.remove(<mekanism:teleportationcore>);
recipes.remove(<appliedenergistics2:condenser>);
recipes.remove(<appliedenergistics2:io_port>);
recipes.remove(<appliedenergistics2:grindstone>);
recipes.remove(<trashcans:liquid_trash_can>);
recipes.remove(<trashcans:energy_trash_can>);
recipes.remove(<trashcans:item_trash_can>);
recipes.remove(<appliedenergistics2:material:2>);
recipes.remove(<tanaddons:thirst_quencher>);
recipes.remove(<toughasnails:charcoal_filter> * 3);
recipes.remove(<appliedenergistics2:sky_compass>);
recipes.remove(<mekanismgenerators:generator:4>);
recipes.remove(<mekanismgenerators:generator:3>);
recipes.remove(<openmodularturrets:intermediate_tiered>);
recipes.removeShapeless(<davincisvessels:balloon:*>, [<minecraft:wool:*>, <ore:string>]);
recipes.remove(<immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:conveyor"}) * 8);
recipes.remove(<immersiveengineering:metal_device1:13>);
recipes.remove(<immersiveengineering:metal_device1:6> * 8);
recipes.remove(<openmodularturrets:ammo_meta:1> * 64);
recipes.remove(<immersiveengineering:metal_device1:8>);
recipes.remove(<immersiveengineering:wooden_device0:6>);
recipes.remove(<immersiveengineering:stone_decoration:1> * 3);
recipes.remove(<immersiveengineering:stone_decoration:1>);
recipes.remove(<mekanism:transmitter>.withTag({tier: 0}) * 8);
recipes.remove(<immersiveengineering:wooden_device1:1>);
recipes.remove(<chargers:charger:2>);
recipes.remove(<chargers:charger:1>);
recipes.remove(<chargers:charger>);
furnace.remove(<mekanism:ingot:4>);
recipes.remove(<mekanismgenerators:generator>);
recipes.remove(<mekanism:jetpack>);
recipes.removeShaped(<mekanism:flamethrower>, [[<mekanism:ingot:6>, <mekanism:ingot:6>, <mekanism:ingot:6>],[<mekanism:ingot:6>, <mekanism:gastank>.withTag({tier: 0}).onlyWithTag({tier: 0}), <minecraft:flint_and_steel>], [<mekanism:ingot:2>, <mekanism:controlcircuit:1>, <mekanism:ingot:2>]]);
recipes.removeShaped(<mekanism:machineblock2:3>, [[<mekanism:reinforcedalloy>, <mekanism:controlcircuit:2>, <mekanism:reinforcedalloy>],[<minecraft:gold_ingot>, <mekanism:machineblock:9>, <minecraft:gold_ingot>], [<mekanism:reinforcedalloy>, <mekanism:controlcircuit:2>, <mekanism:reinforcedalloy>]]);
recipes.removeShaped(<mekanism:machineblock:2>, [[<mekanism:reinforcedalloy>, <mekanism:controlcircuit:2>, <mekanism:reinforcedalloy>],[<ore:materialStoneTool>, <mekanism:basicblock:8>, <ore:materialStoneTool>], [<mekanism:reinforcedalloy>, <mekanism:controlcircuit:2>, <mekanism:reinforcedalloy>]]);
recipes.removeShaped(<mekanism:machineblock:2>, [[<mekanism:reinforcedalloy>, <mekanism:controlcircuit:2>, <mekanism:reinforcedalloy>],[<minecraft:cobblestone>, <mekanism:basicblock:8>, <minecraft:cobblestone>], [<mekanism:reinforcedalloy>, <mekanism:controlcircuit:2>, <mekanism:reinforcedalloy>]]);
recipes.removeShaped(<mekanism:machineblock:9>, [[<mekanism:enrichedalloy>, <mekanism:controlcircuit:1>, <mekanism:enrichedalloy>],[<mekanism:ingot:1>, <mekanism:machineblock>, <mekanism:ingot:1>], [<mekanism:enrichedalloy>, <mekanism:controlcircuit:1>, <mekanism:enrichedalloy>]]);
recipes.removeShaped(<mekanism:machineblock:1>, [[<mekanism:enrichedalloy>, <mekanism:controlcircuit:1>, <mekanism:enrichedalloy>],[<minecraft:bucket>, <mekanism:basicblock:8>, <minecraft:bucket>], [<mekanism:enrichedalloy>, <mekanism:controlcircuit:1>, <mekanism:enrichedalloy>]]);
recipes.removeShaped(<mekanism:machineblock:3>, [[<minecraft:redstone>, <mekanism:controlcircuit>, <minecraft:redstone>],[<minecraft:lava_bucket>, <mekanism:basicblock:8>, <minecraft:lava_bucket>], [<minecraft:redstone>, <mekanism:controlcircuit>, <minecraft:redstone>]]);
//Don't touch me!
//#Add
recipes.addShaped(<quark:rune>, [[<quark:crystal>, <quark:crystal>, <quark:crystal>],[<quark:crystal>, <minecraft:nether_star>, <quark:crystal>], [<quark:crystal>, <quark:crystal>, <quark:crystal>]]);
recipes.addShaped(<quark:rune:1>, [[<quark:crystal:2>, <quark:crystal:2>, <quark:crystal:2>],[<quark:crystal:2>, <tconstruct:materials:11>, <quark:crystal:2>], [<quark:crystal:2>, <quark:crystal:2>, <quark:crystal:2>]]);
recipes.addShaped(<quark:rune:2>, [[<quark:crystal:7>, <quark:crystal:7>, <quark:crystal:7>],[<quark:crystal:7>, <ee:lamented>, <quark:crystal:7>], [<quark:crystal:7>, <quark:crystal:7>, <quark:crystal:7>]]);
recipes.addShaped(<quark:rune:3>, [[<quark:crystal:5>, <quark:crystal:5>, <quark:crystal:5>],[<quark:crystal:5>, <mowziesmobs:ice_crystal>, <quark:crystal:5>], [<quark:crystal:5>, <quark:crystal:5>, <quark:crystal:5>]]);
recipes.addShaped(<quark:rune:4>, [[<quark:crystal:3>, <quark:crystal:3>, <quark:crystal:3>],[<quark:crystal:3>, <mowziesmobs:barako_mask>, <quark:crystal:3>], [<quark:crystal:3>, <quark:crystal:3>, <quark:crystal:3>]]);
recipes.addShaped(<quark:rune:11>, [[<quark:crystal:6>, <quark:crystal:6>, <quark:crystal:6>],[<quark:crystal:6>, <netherex:rime_crystal>, <quark:crystal:6>], [<quark:crystal:6>, <quark:crystal:6>, <quark:crystal:6>]]);
recipes.addShaped(<quark:rune:14>, [[<quark:crystal:1>, <quark:crystal:1>, <quark:crystal:1>],[<quark:crystal:1>, <ee:red_crystal_item>, <quark:crystal:1>], [<quark:crystal:1>, <quark:crystal:1>, <quark:crystal:1>]]);
recipes.addShaped(<quark:rune:5>, [[<quark:crystal:4>, <quark:crystal:4>, <quark:crystal:4>],[<quark:crystal:4>, <mowziesmobs:naga_fang>, <quark:crystal:4>], [<quark:crystal:4>, <quark:crystal:4>, <quark:crystal:4>]]);
recipes.addShaped(<quark:rune:16>, [[<quark:rune:3>, <quark:rune:4>, <quark:rune:5>],[<quark:rune:2>, <appliedenergistics2:material:1>, <quark:rune:11>], [<quark:rune>, <quark:rune:1>, <quark:rune:14>]]);
recipes.addShapeless(<mcwtrpdoors:metal_full_trapdoor>, [<immersiveengineering:metal:8>,<mcwtrpdoors:metal_trapdoor>]);
recipes.addShaped(<mcwtrpdoors:metal_trapdoor>, [[null, <minecraft:iron_trapdoor>, null],[<immersiveengineering:metal:8>, <diamondglass:diamond_glass>, <immersiveengineering:metal:8>], [<immersiveengineering:metal:8>, <diamondglass:diamond_glass>, <immersiveengineering:metal:8>]]);
recipes.addShaped(<mcwdoors:metal_reinforced_door>, [[<tconstruct:ingots:2>, null, <tconstruct:ingots:2>],[<tconstruct:ingots:2>, <mcwdoors:metal_door>, <tconstruct:ingots:2>], [<tconstruct:ingots:2>, null, <tconstruct:ingots:2>]]);
recipes.addShaped(<mcwdoors:metal_door>, [[<immersiveengineering:metal:8>, <immersiveengineering:metal:8>, null],[<immersiveengineering:metal:8>, <minecraft:iron_door>, null], [<immersiveengineering:metal:8>, <immersiveengineering:metal:8>, null]]);
recipes.addShapeless(<craftable_ender_pearls:soul_in_a_bottle> * 2, [<minecraft:soul_sand>,<ore:cofh:potion>]);
recipes.addShaped(<immersiveengineering:metal:8>, [[<mekanism:shard:2>, <mekanism:shard:2>, <mekanism:shard:2>],[<mekanism:clump>, <mekanism:shard:2>, <mekanism:clump>], [null, <mekanism:clump>, null]]);
recipes.addShaped(<srparasites:ada_devourer_drop>, [[null, null, null],[<nocubessrpnests:wormacid>, null, <nocubessrpnests:organicsample>], [<nocubessrpnests:organicsample>, <srparasites:dried_tendons>, <nocubessrpnests:wormacid>]]);
recipes.addShaped(<travelersbackpack:travelers_backpack:22>, [[<additions:srpcustom-infested_eye>, <ee:lamented>, <additions:srpcustom-infested_eye>],[<minecraft:ender_eye>, <travelersbackpack:travelers_backpack>, <minecraft:ender_eye>], [<minecraft:ender_eye>, <minecraft:ender_eye>, <minecraft:ender_eye>]]);
recipes.addShapeless(<appliedenergistics2:material:48> * 2, [<appliedenergistics2:material:47>,<appliedenergistics2:material:46>,<appliedenergistics2:material:46>,<appliedenergistics2:tiny_tnt>]);
recipes.addShaped(<swparasites:hardened_bone_pole>, [[<srparasites:assimilated_flesh>, <nocubessrparmory:carbonsteel>, <srparasites:hardened_bone_handle>],[<nocubessrparmory:carbonsteel>, <srparasites:hardened_bone_handle>, <nocubessrparmory:carbonsteel>], [<srparasites:hardened_bone_handle>, <nocubessrparmory:carbonsteel>, <srparasites:assimilated_flesh>]]);
recipes.addShapeless(<mekanism:ingot:3> * 8, [<mekanism:basicblock:4>]);
recipes.addShaped(<swparasites:infectious_long_blade_fragment>, [[<nocubessrparmory:carbonsteel>, <srparasites:hardened_bone_handle>, <nocubessrparmory:carbonsteel>],[<nocubessrparmory:carbonsteel>, <srparasites:hardened_bone_handle>, <nocubessrparmory:carbonsteel>], [<nocubessrparmory:carbonsteel>, <srparasites:hardened_bone_handle>, <nocubessrparmory:carbonsteel>]]);
recipes.addShaped(<srparasites:evolutionlure>, [[<srparasites:lurecomponent1>, <srparasites:lurecomponent2>, <srparasites:lurecomponent1>],[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShapeless(<nocubessrparmory:twistedpart> * 2, [<srparasites:lurecomponent1>,<ore:dyeBlack>,<minecraft:string>]);
recipes.addShaped(<betterbuilderswands:wandunbreakable>, [[null, null, <minecraft:nether_star>],[null, <immersiveengineering:material>, null], [<immersiveengineering:material>, null, null]]);
recipes.addShaped(<betterbuilderswands:wandiron>, [[null, null, <minecraft:iron_ingot>],[null, <immersiveengineering:material>, null], [<immersiveengineering:material>, null, null]]);
recipes.addShaped(<betterbuilderswands:wanddiamond>, [[null, null, <minecraft:diamond>],[null, <immersiveengineering:material>, null], [<immersiveengineering:material>, null, null]]);
recipes.addShaped(<betterbuilderswands:wandstone>, [[null, null, <minecraft:cobblestone>],[null, <immersiveengineering:material>, null], [<immersiveengineering:material>, null, null]]);
recipes.addShapeless(<quark:obsidian_pressure_plate>, [<playerplates:obsidian_plate>]);
recipes.addShapeless(<playerplates:obsidian_plate>, [<quark:obsidian_pressure_plate>]);
recipes.addShaped(<xplosives:packed_tnt>, [[<minecraft:tnt>, <minecraft:tnt>, <minecraft:tnt>],[<minecraft:tnt>, <immersiveengineering:material:25>, <minecraft:tnt>], [<minecraft:tnt>, <minecraft:tnt>, <minecraft:tnt>]]);
recipes.addShaped(<xplosives:hand_cannon>, [[<immersiveengineering:metal:8>, <immersiveengineering:metal:8>, <immersiveengineering:metal:8>],[<minecraft:gunpowder>, <mekanism:reinforcedalloy>, <immersiveengineering:metal:8>], [<immersiveengineering:metal:8>, null, null]]);
recipes.addShaped(<xplosives:detonator>, [[null, <immersiveengineering:metal:8>, null],[null, <minecraft:redstone_torch>, null], [null, <immersiveengineering:metal:8>, null]]);
recipes.addShaped(<xplosives:detonator_remote>, [[<immersiveengineering:metal:8>, <minecraft:redstone_torch>, <immersiveengineering:metal:8>],[<immersiveengineering:metal:8>, <mekanism:enrichedalloy>, <immersiveengineering:metal:8>], [<immersiveengineering:metal:8>, <immersiveengineering:metal:8>, <immersiveengineering:metal:8>]]);
recipes.addShaped(<xplosives:physics_bomb> * 4, [[<minecraft:tnt>, <minecraft:tnt>, <minecraft:tnt>],[<minecraft:tnt>, <minecraft:ender_pearl>, <minecraft:tnt>], [<minecraft:tnt>, <minecraft:tnt>, <minecraft:tnt>]]);
recipes.addShaped(<xplosives:arrow_bomb>, [[<minecraft:tnt>, <minecraft:tnt>, <minecraft:tnt>],[<minecraft:tnt>, <minecraft:arrow>, <minecraft:tnt>], [<minecraft:tnt>, <minecraft:tnt>, <minecraft:tnt>]]);
recipes.addShapeless(<xplosives:bonemeal_bomb>, [<minecraft:dye:15>,<minecraft:tnt>]);
recipes.addShapeless(<xplosives:dynamite>, [<immersiveengineering:material:4>,<minecraft:tnt>]);
recipes.addShaped(<ee:obi_coin>, [[<ee:purple_crystal_item>, <ee:purple_crystal_item>, <ee:purple_crystal_item>],[<ee:purple_crystal_item>, <ee:infusion_core>, <ee:red_crystal_item>], [<ee:red_crystal_item>, <ee:red_crystal_item>, <ee:red_crystal_item>]]);
recipes.addShaped(<ee:mod_arrow_unholy> * 4, [[null, <ee:red_chunk>, null],[null, <ee:brick_rod>, null], [null, <ee:amber_ingot>, null]]);
recipes.addShaped(<travelersbackpack:travelers_backpack:57>, [[<ore:dyeOrange>, <xat:mana_crystal>, <ore:dyeYellow>],[<ore:dyePurple>, <travelersbackpack:travelers_backpack>, <ore:dyeRed>], [<ore:dyeCyan>, <ore:dyeBlue>, <ore:dyeLime>]]);
recipes.addShapeless(<gbook:guidebook>.withTag({Book: "gbook:calamity introduction.xml"}), [<srparasites:assimilated_flesh>,<minecraft:book>]);
recipes.addShaped(<mowziesmobs:earth_talisman>, [[<ee:infused_crystal>, <ee:infused_crystal>, <ee:infused_crystal>],[<mowziesmobs:ice_crystal>.anyDamage(), <ee:soul>, <mowziesmobs:ice_crystal>.anyDamage()], [<xat:mana_crystal>, <xat:mana_crystal>, <xat:mana_crystal>]]);
recipes.addShaped(<ee:end_door>, [[<ee:red_chunk>, <ee:ash_brick>, <ee:red_chunk>],[<ee:ash_brick>, <ee:red_crystal_item>, <ee:ash_brick>], [<tconstruct:ingots:2>, <minecraft:redstone>, <tconstruct:ingots:2>]]);
recipes.addShapedMirrored(<mowziesmobs:dart>, [[null, null, null],[null, <minecraft:iron_ingot>, null], [<futuremc:bamboo>, null, null]]);
recipes.addShapedMirrored(<mowziesmobs:spear>, [[null, <minecraft:string>, <minecraft:iron_ingot>],[null, <futuremc:bamboo>, <minecraft:string>], [<futuremc:bamboo>, null, null]]);
recipes.addShapedMirrored(<mowziesmobs:blowgun>, [[null, null, null],[<futuremc:bamboo>, <futuremc:bamboo>, <futuremc:bamboo>], [null, null, null]]);
recipes.addShaped(<swparasites:buckler_shield_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:overlordcore>, <swparasites:buckler_shield_living>.anyDamage(), <nocubessrparmory:overlordcore>], [<additions:srpcustom-infested_eye>, <swparasites:living_nucleus>, <additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:impaler_shield_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:overlordcore>, <swparasites:impaler_shield_living>.anyDamage(), <nocubessrparmory:overlordcore>], [<additions:srpcustom-infested_eye>, <swparasites:living_nucleus>, <additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:crossbow_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:dreadnaughtcore>, <swparasites:crossbow_living>.anyDamage(), <nocubessrparmory:dreadnaughtcore>], [<additions:srpcustom-infested_eye>, <swparasites:living_nucleus>, <additions:srpcustom-infested_eye>]]);
recipes.addShaped(<additions:srpcustom-link>, [[<immersiveengineering:metal:8>, <immersiveengineering:metal:8>, <immersiveengineering:metal:8>],[<additions:srpcustom-organic_rod>, <appliedenergistics2:material:47>, <additions:srpcustom-acid_rod>], [null, <nocubessrparmory:infestedtoolrod>, null]]);
recipes.addShaped(<additions:srpcustom-yelloweye_block>, [[<srparasites:bone>, <srparasites:ada_yelloweye_drop>, <srparasites:bone>],[<minecraft:obsidian>, <minecraft:glowstone_dust>, <minecraft:obsidian>], [<srparasites:bone>, <srparasites:ada_yelloweye_drop>, <srparasites:bone>]]);
recipes.addShaped(<wings:dragon_wings>, [[<minecraft:dragon_breath>, <xat:moon_rose>, <minecraft:dragon_breath>],[<minecraft:gold_ingot>, <wings:fairy_dust>, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, <minecraft:elytra>.anyDamage(), <minecraft:gold_ingot>]]);
recipes.addShaped(<wings:evil_wings>, [[<ore:gemEmerald>, <xat:moon_rose>, <ore:gemAmethyst>],[<minecraft:gold_ingot>, <wings:fairy_dust>, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, <minecraft:elytra>.anyDamage(), <minecraft:gold_ingot>]]);
recipes.addShaped(<wings:fairy_wings>, [[<minecraft:red_flower:7>, <xat:moon_rose>, <minecraft:red_flower:8>],[<minecraft:gold_ingot>, <wings:fairy_dust>, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, <minecraft:elytra>.anyDamage(), <minecraft:gold_ingot>]]);
recipes.addShaped(<wings:bat_wings>, [[<wings:bat_blood>, <xat:moon_rose>, <wings:bat_blood>],[<minecraft:gold_ingot>, <wings:fairy_dust>, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, <minecraft:elytra>.anyDamage(), <minecraft:gold_ingot>]]);
recipes.addShaped(<wings:fire_wings>, [[<ore:dustBlaze>, <xat:moon_rose>, <ore:dustBlaze>],[<minecraft:gold_ingot>, <wings:fairy_dust>, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, <minecraft:elytra>.anyDamage(), <minecraft:gold_ingot>]]);
recipes.addShaped(<wings:monarch_butterfly_wings>, [[<ore:dyeBlack>, <xat:moon_rose>, <ore:dyeOrange>],[<minecraft:gold_ingot>, <wings:fairy_dust>, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, <minecraft:elytra>.anyDamage(), <minecraft:gold_ingot>]]);
recipes.addShaped(<wings:blue_butterfly_wings>, [[<ore:dyeBlack>, <xat:moon_rose>, <ore:dyeBlue>],[<minecraft:gold_ingot>, <wings:fairy_dust>, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, <minecraft:elytra>.anyDamage(), <minecraft:gold_ingot>]]);
recipes.addShaped(<wings:slime_wings>, [[<ore:slimeball>, <xat:moon_rose>, <ore:slimeball>],[<minecraft:gold_ingot>, <wings:fairy_dust>, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, <minecraft:elytra>.anyDamage(), <minecraft:gold_ingot>]]);
recipes.addShaped(<wings:angel_wings>, [[<ore:feather>, <xat:moon_rose>, <ore:feather>],[<minecraft:gold_ingot>, <wings:fairy_dust>, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, <minecraft:elytra>.anyDamage(), <minecraft:gold_ingot>]]);
recipes.addShapeless(<minecraft:fireworks>, [<minecraft:gunpowder>,<minecraft:paper>]);
recipes.addShaped(<additions:srpcustom-skull_of_creation>, [[<srparasites:bone>, <srparasites:bone>, <srparasites:bone>],[<srparasites:bone>, <xat:mana_crystal>, <srparasites:bone>], [null, null, null]]);
recipes.addShaped(<additions:srpcustom-reinforced_balloon> * 8, [[<davincisvessels:balloon:*>, <davincisvessels:balloon:*>, <davincisvessels:balloon:*>],[<davincisvessels:balloon:*>, <rbm2:obsidianupgrade>, <davincisvessels:balloon:*>], [<davincisvessels:balloon:*>, <davincisvessels:balloon:*>, <davincisvessels:balloon:*>]]);
recipes.addShaped(<tconstruct:slime_boots:3>, [[null, null, null],[<tconstruct:edible:3>, null, <tconstruct:edible:3>], [<tconstruct:ingots:3>, <tconstruct:ingots:3>, <tconstruct:ingots:3>]]);
recipes.addShaped(<minecraft:bread>, [[null, null, null],[<minecraft:wheat>, <minecraft:wheat>, <minecraft:wheat>], [null, null, null]]);
recipes.addShaped(<tconstruct:slime_boots:1>, [[null, null, null],[<tconstruct:edible:1>, null, <tconstruct:edible:1>], [<tconstruct:ingots:3>, <tconstruct:ingots:3>, <tconstruct:ingots:3>]]);
recipes.addShaped(<tconstruct:slime_boots:4>, [[null, null, null],[<tconstruct:edible:4>, null, <tconstruct:edible:4>], [<tconstruct:ingots:3>, <tconstruct:ingots:3>, <tconstruct:ingots:3>]]);
recipes.addShaped(<tconstruct:slime_boots>, [[null, null, null],[<minecraft:slime_ball>, null, <minecraft:slime_ball>], [<tconstruct:ingots:3>, <tconstruct:ingots:3>, <tconstruct:ingots:3>]]);
recipes.addShaped(<tconstruct:slime_boots:2>, [[null, null, null],[<tconstruct:edible:2>, null, <tconstruct:edible:2>], [<tconstruct:ingots:3>, <tconstruct:ingots:3>, <tconstruct:ingots:3>]]);
recipes.addShaped(<tconstruct:slimesling:1>, [[<minecraft:string>, <tconstruct:metal:3>, <minecraft:string>],[<tconstruct:edible:1>, null, <tconstruct:edible:1>], [null, <tconstruct:edible:1>, null]]);
recipes.addShaped(<tconstruct:slimesling>, [[<minecraft:string>, <tconstruct:metal:3>, <minecraft:string>],[<minecraft:slime_ball>, null, <minecraft:slime_ball>], [null, <minecraft:slime_ball>, null]]);
recipes.addShaped(<tconstruct:slimesling:2>, [[<minecraft:string>, <tconstruct:metal:3>, <minecraft:string>],[<tconstruct:edible:2>, null, <tconstruct:edible:2>], [null, <tconstruct:edible:2>, null]]);
recipes.addShaped(<tconstruct:slimesling:3>, [[<minecraft:string>, <tconstruct:metal:3>, <minecraft:string>],[<tconstruct:edible:3>, null, <tconstruct:edible:3>], [null, <tconstruct:edible:3>, null]]);
recipes.addShaped(<tconstruct:slimesling:4>, [[<minecraft:string>, <tconstruct:metal:3>, <minecraft:string>],[<tconstruct:edible:4>, null, <tconstruct:edible:4>], [null, <tconstruct:edible:4>, null]]);
recipes.addShaped(<srparasites:evolutionlure:9>, [[<nocubessrparmory:dreadnaughtcore>, <srparasites:evolutionlure:8>, <nocubessrparmory:overlordcore>],[<srparasites:evolutionlure:8>, <srparasites:evolutionlure:8>, <srparasites:evolutionlure:8>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<srparasites:evolutionlure:8>, [[<nocubessrparmory:dreadnaughtcore>, <srparasites:evolutionlure:7>, <nocubessrparmory:overlordcore>],[<srparasites:evolutionlure:7>, <srparasites:evolutionlure:7>, <srparasites:evolutionlure:7>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<srparasites:evolutionlure:7>, [[<nocubessrparmory:dreadnaughtcore>, <srparasites:evolutionlure:6>, <nocubessrparmory:overlordcore>],[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<srparasites:evolutionlure:6>, [[<srparasites:lurecomponent6>, <srparasites:evolutionlure:5>, <srparasites:lurecomponent6>],[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<srparasites:evolutionlure:5>, [[<srparasites:lurecomponent5>, null, <srparasites:lurecomponent5>],[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<srparasites:evolutionlure:4>, [[<srparasites:lurecomponent4>, null, <srparasites:lurecomponent4>],[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<srparasites:evolutionlure:3>, [[<srparasites:lurecomponent3>, <srparasites:evolutionlure:2>, <srparasites:lurecomponent3>],[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<srparasites:evolutionlure:2>, [[<srparasites:dispatcher_drop>, null, <srparasites:dispatcher_drop>],[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<srparasites:evolutionlure:2>, [[<srparasites:beckon_drop>, null, <srparasites:beckon_drop>],[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShapeless(<bountifulbaubles:shieldankh>, [<bountifulbaubles:shieldobsidian>,<bountifulbaubles:trinketankhcharm>,<spartanshields:shield_basic_signalum>]);
recipes.addShaped(<bountifulbaubles:trinketblackdragonscale>, [[<bountifulbaubles:brokenblackdragonscale>, <bountifulbaubles:enderdragonscale>, <bountifulbaubles:brokenblackdragonscale>],[<minecraft:nether_star>, <bountifulbaubles:enderdragonscale>, <minecraft:nether_star>], [<bountifulbaubles:brokenblackdragonscale>, <bountifulbaubles:enderdragonscale>, <bountifulbaubles:brokenblackdragonscale>]]);
recipes.addShaped(<improvableskills:skills_book>, [[<xat:mana_candy>, <minecraft:leather>, <xat:mana_candy>],[<minecraft:book>, <minecraft:gold_ingot>, <minecraft:book>], [<xat:mana_candy>, <minecraft:leather>, <xat:mana_candy>]]);
recipes.addShaped(<swparasites:warhammer_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:warhammer_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:throwing_knife_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:throwing_knife_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:longsword_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:longsword_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:mace_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:mace_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:parrying_dagger_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:parrying_dagger_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:pike_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:pike_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:saber_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:saber_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:staff_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:staff_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:rapier_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:rapier_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:spear_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:spear_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:throwing_axe_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:throwing_axe_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<mujmajnkraftsbettersurvival:iteminvarnunchaku>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <mujmajnkraftsbettersurvival:itemsignalumnunchaku>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:claymore_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:dreadnaughtcore>, <swparasites:claymore_living>.anyDamage(), <nocubessrparmory:overlordcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:dagger_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:dagger_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:boomerang_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:boomerang_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:glaive_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:glaive_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:halberd_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:overlordcore>, <swparasites:halberd_living>.anyDamage(), <nocubessrparmory:dreadnaughtcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:hammer_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:hammer_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:javelin_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:javelin_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<swparasites:katana_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<hermitsarsenal:wrathful_core>, <swparasites:katana_living>.anyDamage(), <hermitsarsenal:wrathful_core>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShapeless(<eplus:advanced_table>, [<minecraft:enchanting_table>,<eplus:table_upgrade>]);
recipes.addShaped(<eplus:table_upgrade>, [[<oresabovediamonds:black_opal>, <minecraft:writable_book>, <oresabovediamonds:black_opal>],[<minecraft:obsidian>, null, <minecraft:obsidian>], [<oresabovediamonds:amethyst>, <additions:srpcustom-infested_eye>, <oresabovediamonds:amethyst>]]);
recipes.addShaped(<eplus:advanced_table>, [[<oresabovediamonds:black_opal>, <minecraft:writable_book>, <oresabovediamonds:black_opal>],[<minecraft:obsidian>, <minecraft:enchanting_table>, <minecraft:obsidian>], [<oresabovediamonds:amethyst>, <additions:srpcustom-infested_eye>, <oresabovediamonds:amethyst>]]);
recipes.addShaped(<srparasites:armor_boots_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:overlordcore>, <srparasites:armor_boots>.anyDamage(), <nocubessrparmory:dreadnaughtcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<srparasites:armor_pants_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:overlordcore>, <srparasites:armor_pants>.anyDamage(), <nocubessrparmory:dreadnaughtcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<srparasites:armor_chest_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:overlordcore>, <srparasites:armor_chest>.anyDamage(), <nocubessrparmory:dreadnaughtcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<srparasites:armor_helm_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:overlordcore>, <srparasites:armor_helm>.anyDamage(), <nocubessrparmory:dreadnaughtcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<srparasites:weapon_sword_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:overlordcore>, <srparasites:weapon_sword>.anyDamage(), <nocubessrparmory:dreadnaughtcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<srparasites:weapon_scythe_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:overlordcore>, <srparasites:weapon_scythe>.anyDamage(), <nocubessrparmory:overlordcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<srparasites:weapon_axe_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:overlordcore>, <srparasites:weapon_axe>.anyDamage(), <nocubessrparmory:overlordcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<srparasites:weapon_maul_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:overlordcore>, <srparasites:weapon_maul>.anyDamage(), <nocubessrparmory:overlordcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<srparasites:weapon_cleaver_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:dreadnaughtcore>, <srparasites:weapon_cleaver>.anyDamage(), <nocubessrparmory:dreadnaughtcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<srparasites:weapon_bow_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:dreadnaughtcore>, <srparasites:weapon_bow>.anyDamage(), <nocubessrparmory:dreadnaughtcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<srparasites:weapon_lance_sentient>, [[<srparasites:lurecomponent6>, <srparasites:lurecomponent5>, <srparasites:lurecomponent6>],[<nocubessrparmory:dreadnaughtcore>, <srparasites:weapon_lance>.anyDamage(), <nocubessrparmory:dreadnaughtcore>], [<additions:srpcustom-infested_eye>,<swparasites:living_nucleus>,<additions:srpcustom-infested_eye>]]);
recipes.addShaped(<mekanism:basicblock2:9>, [[<immersiveengineering:metal:8>, <ore:blockGlass>, <immersiveengineering:metal:8>],[<immersiveengineering:metal:8>, <mekanism:basicblock:8>, <immersiveengineering:metal:8>], [<immersiveengineering:metal:8>, null, <immersiveengineering:metal:8>]]);
recipes.addShaped(<mekanism:teleportationcore>, [[<appliedenergistics2:material:7>, <mekanism:atomicalloy>, <appliedenergistics2:material:7>],[<appliedenergistics2:material:7>, <appliedenergistics2:material:48>, <appliedenergistics2:material:7>], [<appliedenergistics2:material:7>, <mekanism:atomicalloy>, <appliedenergistics2:material:7>]]);
recipes.addShaped(<appliedenergistics2:condenser>, [[<appliedenergistics2:material:10>, <ore:blockGlass>, <appliedenergistics2:material:10>],[<ore:blockGlass>, <oresabovediamonds:black_opal>, <ore:blockGlass>], [<appliedenergistics2:material:10>, <ore:blockGlass>, <appliedenergistics2:material:10>]]);
recipes.addShaped(<appliedenergistics2:io_port>, [[<ore:blockGlass>, <ore:blockGlass>, <ore:blockGlass>],[<appliedenergistics2:part:380>, <appliedenergistics2:part:16>, <appliedenergistics2:drive>], [<ore:ingotIron>, <appliedenergistics2:material:22>, <ore:ingotIron>]]);
recipes.addShaped(<appliedenergistics2:grindstone>, [[<minecraft:stone>, <minecraft:stone>, <minecraft:stone>],[<appliedenergistics2:material>, <minecraft:iron_ingot>, <appliedenergistics2:material>], [<minecraft:iron_ingot>, <appliedenergistics2:material>, <minecraft:iron_ingot>]]);
recipes.addShaped(<trashcans:energy_trash_can>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>],[<ore:ingotIron>, <minecraft:redstone>, <ore:ingotIron>], [<immersiveengineering:treated_wood:0>, <immersiveengineering:treated_wood:0>, <immersiveengineering:treated_wood:0>]]);
recipes.addShaped(<trashcans:liquid_trash_can>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>],[<ore:ingotIron>, <minecraft:bucket>, <ore:ingotIron>], [<immersiveengineering:treated_wood:0>, <immersiveengineering:treated_wood:0>, <immersiveengineering:treated_wood:0>]]);
recipes.addShaped(<trashcans:item_trash_can>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>],[<ore:ingotIron>, <minecraft:chest>, <ore:ingotIron>], [<immersiveengineering:treated_wood:0>, <immersiveengineering:treated_wood:0>, <immersiveengineering:treated_wood:0>]]);
recipes.addShaped(<tanaddons:thirst_quencher>.withTag({FluidStored: 0, ForgeEnergy: 0, TimeStart: 100}), [[<immersiveengineering:material:5>, <toughasnails:charcoal_filter>, <immersiveengineering:material:5>],[<ore:ingotIron>, <toughasnails:canteen>, <ore:ingotIron>], [<ore:ingotIron>, <minecraft:potion>.withTag({Potion: "minecraft:water"}).onlyWithTag({Potion: "minecraft:water"}), <ore:ingotIron>]]);
recipes.addShaped(<toughasnails:charcoal_filter> * 9, [[null, <minecraft:paper>, null],[null, <minecraft:coal:1>, null], [null, <minecraft:paper>, null]]);
recipes.addShaped(<appliedenergistics2:sky_compass>, [[null, <mekanism:enrichedalloy>, null],[<mekanism:enrichedalloy>, <appliedenergistics2:material:1>, <mekanism:enrichedalloy>], [null, <mekanism:enrichedalloy>, null]]);
recipes.addShaped(<mekanismgenerators:generator:4>, [[<mekanism:enrichedalloy>, <ore:alloyBasic>, <mekanism:enrichedalloy>],[<ore:itemBioFuel>, <mekanism:controlcircuit>, <ore:itemBioFuel>], [<ore:ingotIron>, <mekanism:energytablet>, <ore:ingotIron>]]);
recipes.addShaped(<mekanismgenerators:generator:3>, [[<ore:ingotOsmium>, <mekanism:enrichedalloy>, <ore:ingotOsmium>],[<mekanism:basicblock:8>, <mekanism:electrolyticcore>, <mekanism:basicblock:8>], [<mekanism:energytablet>, <mekanism:enrichedalloy>, <mekanism:energytablet>]]);
recipes.addShaped(<openmodularturrets:intermediate_tiered>, [[null, <minecraft:redstone>, null],[<minecraft:redstone>, <immersiveengineering:treated_wood>, <minecraft:redstone>], [null, <minecraft:redstone>, null]]);
recipes.addShapeless(<davincisvessels:balloon>, [<minecraft:wool>, <ore:fiberHemp>]);
recipes.addShapeless(<immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:conveyor"}), [<immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:uncontrolled"}).onlyWithTag({conveyorType: "immersiveengineering:uncontrolled"})]);
recipes.addShaped(<immersiveengineering:conveyor>.withTag({conveyorType: "immersiveengineering:conveyor"}) * 8, [[null, null, null],[<minecraft:leather>, <immersiveengineering:material:4>, <minecraft:leather>], [<minecraft:iron_ingot>, <minecraft:redstone>, <minecraft:iron_ingot>]]);
recipes.addShaped(<immersiveengineering:metal_device1:13>, [[<ore:blockGlass>, <immersiveengineering:material:26>, <ore:blockGlass>],[<ore:blockGlass>, <ore:fiberHemp>, <ore:blockGlass>], [<immersiveengineering:treated_wood>, <immersiveengineering:material:8>, <immersiveengineering:treated_wood>]]);
recipes.addShaped(<immersiveengineering:metal_device1:6> * 16, [[<immersiveengineering:metal:39>, <immersiveengineering:metal:39>, <immersiveengineering:metal:39>],[null, null, null], [<immersiveengineering:metal:39>, <immersiveengineering:metal:39>, <immersiveengineering:metal:39>]]);
recipes.addShaped(<openmodularturrets:ammo_meta:1> * 16, [[null, <ore:ingotOsmium>, null],[null, <ore:gunpowder>, null], [null, <ore:ingotIron>, null]]);
recipes.addShaped(<immersiveengineering:metal_device1:8>, [[<ore:ingotAluminum>, <ore:ingotAluminum>, <ore:ingotAluminum>],[null, <immersiveengineering:metal_decoration0>, null], [<immersiveengineering:metal_device0:2>, <immersiveengineering:wooden_device0:6>, <immersiveengineering:metal_device0:2>]]);
recipes.addShaped(<immersiveengineering:wooden_device0:6>, [[null, null, null],[<immersiveengineering:treated_wood>, <ore:ingotSteel>, <immersiveengineering:treated_wood>], [<ore:circuitAdvanced>, <immersiveengineering:metal_decoration0>, <ore:circuitAdvanced>]]);
recipes.addShaped(<immersiveengineering:stone_decoration:1> * 3, [[<ore:ingotBrickNether>, <ore:ingotBrick>, <ore:ingotBrickNether>],[<ore:ingotBrick>, <ore:plankTreatedWood>, <ore:ingotBrick>], [<ore:ingotBrickNether>, <ore:ingotBrick>, <ore:ingotBrickNether>]]);
recipes.addShaped(<mekanism:transmitter>.withTag({tier: 0}) * 8, [[null, null, null],[<ore:ingotIron>, <ore:circuitBasic>, <ore:ingotIron>], [null, null, null]]);
recipes.addShaped(<immersiveengineering:wooden_device1:1>, [[<immersiveengineering:material:11>, <immersiveengineering:material:11>, <immersiveengineering:material:11>],[<immersiveengineering:material:11>, <immersiveengineering:metal:8>, <immersiveengineering:material:11>], [<immersiveengineering:material:11>, <immersiveengineering:material:11>, <immersiveengineering:material:11>]]);
recipes.addShaped(<chargers:charger:2>, [[<ore:gemDiamond>, <ore:gemBlackOpal>, <ore:gemDiamond>],[<ore:gemDiamond>, <chargers:charger:1>, <ore:gemDiamond>], [<ore:gemDiamond>, <ore:blockSteel>, <ore:gemDiamond>]]);
recipes.addShaped(<chargers:charger:1>, [[<ore:ingotGold>, <oresabovediamonds:amethyst>, <ore:ingotGold>],[<ore:ingotGold>, <chargers:charger>, <ore:ingotGold>], [<ore:ingotGold>, <ore:blockSteel>, <ore:ingotGold>]]);
recipes.addShaped(<chargers:charger>, [[<ore:ingotIron>, <ore:ingotSteel>, <ore:ingotIron>],[<ore:ingotIron>, <ore:blockRedstone>, <ore:ingotIron>], [<ore:ingotIron>, <ore:ingotSteel>, <ore:ingotIron>]]);
furnace.addRecipe(<immersiveengineering:metal:8>, <mekanism:otherdust:1>, 0.5);
recipes.addShaped(<mekanismgenerators:generator>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>],[<ore:plankWood>, <mekanism:energytablet>, <ore:plankWood>], [<ore:ingotCopper>, <minecraft:furnace>, <ore:ingotCopper>]]);
recipes.addShaped(<mekanism:jetpack>, [[<ore:ingotSteel>, <ore:alloyUltimate>, <ore:ingotSteel>],[<ore:ingotTin>, <mekanism:gastank>.withTag({tier: 3}).onlyWithTag({tier: 3}), <ore:ingotTin>], [<ore:ingotElectrum>, <ore:ingotTin>, <ore:ingotElectrum>]]);
recipes.addShaped(<immersiveengineering:blueprint>.withTag({blueprint: "specialBullet"}), [[<xat:glowing_powder>, <minecraft:dragon_breath>, <xat:glowing_powder>],[<ore:dyeBlue>, <ore:dyeBlue>, <ore:dyeBlue>], [<minecraft:paper>, <minecraft:paper>, <minecraft:paper>]]);
recipes.addShaped(<immersiveengineering:blueprint>.withTag({blueprint: "electrode"}), [[<immersiveengineering:material:19>, <immersiveengineering:material:19>, <immersiveengineering:material:19>],[<ore:dyeBlue>, <ore:dyeBlue>, <ore:dyeBlue>], [<minecraft:paper>, <minecraft:paper>, <minecraft:paper>]]);
recipes.addShaped(<mekanism:flamethrower>, [[<immersiveengineering:metal:1>, <immersiveengineering:metal:1>, <immersiveengineering:metal:1>],[<immersiveengineering:metal:1>, <mekanism:gastank>.withTag({tier: 2}).onlyWithTag({tier: 2}), <minecraft:flint_and_steel>], [<immersiveengineering:metal:36>, <mekanism:controlcircuit:3>, <immersiveengineering:metal:36>]]);
recipes.addShaped(<mekanism:machineblock2:3>, [[<mekanism:reinforcedalloy>, <mekanism:controlcircuit:2>, <mekanism:reinforcedalloy>],[<forge:bucketfilled>.withTag({FluidName: "biodiesel", Amount: 1000}).onlyWithTag({FluidName: "biodiesel", Amount: 1000}), <mekanism:clump:2>, <forge:bucketfilled>.withTag({FluidName: "biodiesel", Amount: 1000}).onlyWithTag({FluidName: "biodiesel", Amount: 1000})], [<mekanism:reinforcedalloy>, <mekanism:controlcircuit:2>, <mekanism:reinforcedalloy>]]);
recipes.addShaped(<mekanism:machineblock:2>, [[<minecraft:redstone>, <mekanism:controlcircuit>, <minecraft:redstone>],[<ore:materialStoneTool>, <mekanism:basicblock:8>, <ore:materialStoneTool>], [<minecraft:redstone>, <mekanism:controlcircuit>, <minecraft:redstone>]]);
recipes.addShaped(<mekanism:machineblock:9>, [[<mekanism:enrichedalloy>, <mekanism:controlcircuit:1>, <mekanism:enrichedalloy>],[<forge:bucketfilled>.withTag({FluidName: "ethanol", Amount: 1000}).onlyWithTag({FluidName: "ethanol", Amount: 1000}), <immersiveengineering:storage:8>, <forge:bucketfilled>.withTag({FluidName: "ethanol", Amount: 1000}).onlyWithTag({FluidName: "ethanol", Amount: 1000})], [<mekanism:enrichedalloy>, <mekanism:controlcircuit:1>, <mekanism:enrichedalloy>]]);
recipes.addShaped(<mekanism:machineblock:1>, [[<mekanism:enrichedalloy>, <mekanism:controlcircuit:1>, <mekanism:enrichedalloy>],[<forge:bucketfilled>.withTag({FluidName: "ethanol", Amount: 1000}).onlyWithTag({FluidName: "ethanol", Amount: 1000}), <mekanism:basicblock:8>, <forge:bucketfilled>.withTag({FluidName: "ethanol", Amount: 1000}).onlyWithTag({FluidName: "ethanol", Amount: 1000})], [<mekanism:enrichedalloy>, <mekanism:controlcircuit:1>, <mekanism:enrichedalloy>]]);
recipes.addShaped(<mekanism:machineblock:3>, [[<mekanism:enrichedalloy>, <mekanism:controlcircuit>, <mekanism:enrichedalloy>],[<minecraft:lava_bucket>, <mekanism:basicblock:8>, <minecraft:lava_bucket>], [<mekanism:enrichedalloy>, <mekanism:controlcircuit>, <mekanism:enrichedalloy>]]);
recipes.addShaped(<mekanism:machineblock:11>, [[<mekanism:controlcircuit:3>, <mekanism:basicblock:8>, <mekanism:controlcircuit:3>],[<mekanism:basicblock:8>, <mekanism:machineblock3>, <mekanism:basicblock:8>], [<mekanism:controlcircuit:3>, <mekanism:basicblock:8>, <mekanism:controlcircuit:3>]]);
//File End
